-- Generated by scripts/seed.mts from content/. Do not edit by hand; re-run the script.

begin;

insert into public.portfolio_items (id, title, client, category, format, media, duration, tag, meta, featured, sample, published, sort_order) values
  ('item-1', 'Palm Jumeirah villa', null, 'property', 'reel', '{"alt":"Placeholder reel: villa with pool","placeholder":"villa"}'::jsonb, '0:30', null, 'Property', false, true, true, 1),
  ('item-2', 'Downtown penthouse', null, 'property', 'reel', '{"alt":"Placeholder reel: penthouse at night","placeholder":"night"}'::jsonb, '0:24', null, 'Night', false, true, true, 2),
  ('item-3', 'Adam, market update', null, 'ai-avatar', 'reel', '{"alt":"Placeholder: AI presenter Adam","placeholder":"adam","bright":true}'::jsonb, null, 'Adam · AI', 'AI avatar', false, true, true, 3),
  ('item-4', 'Aesthetic clinic', null, 'brand', 'reel', '{"alt":"Placeholder reel: clinic interior","placeholder":"clinic"}'::jsonb, '0:40', null, 'Brand', false, true, true, 4),
  ('item-5', 'Marina 2BR walkthrough', null, 'property', 'reel', '{"alt":"Placeholder: apartment interior","placeholder":"interior"}'::jsonb, '0:28', 'Marina 2BR', 'Property', false, true, true, 5),
  ('item-6', 'Barber studio', null, 'brand', 'reel', '{"alt":"Placeholder: salon brand reel","placeholder":"salon"}'::jsonb, '0:35', null, 'Brand', false, true, true, 6),
  ('item-7', 'Living room, Dubai Marina 2BR', null, 'property', 'photo', '{"alt":"Placeholder: living room of a 2-bedroom apartment","placeholder":"interior"}'::jsonb, null, 'Dubai Marina · 2BR', 'Photo', false, true, true, 7),
  ('item-8', 'Villa twilight', null, 'editing', 'photo', '{"alt":"Placeholder: twilight conversion of a villa","placeholder":"villa-dusk"}'::jsonb, null, 'Twilight', 'Editing', false, true, true, 8),
  ('item-9', 'HDR kitchen', null, 'editing', 'photo', '{"alt":"Placeholder: HDR kitchen","placeholder":"kitchen"}'::jsonb, null, null, 'Editing', false, true, true, 9),
  ('item-10', 'HDR bathroom', null, 'editing', 'photo', '{"alt":"Placeholder: HDR bathroom","placeholder":"bath"}'::jsonb, null, null, 'Editing', false, true, true, 10),
  ('item-11', 'Villa walkthrough', null, 'editing', 'long-form', '{"alt":"Placeholder: still from a villa walkthrough video","placeholder":"villa-dusk"}'::jsonb, null, null, 'Long-form', false, true, true, 11),
  ('item-12', 'Villa pool', null, 'property', 'photo', '{"alt":"Placeholder: villa pool","placeholder":"villa"}'::jsonb, null, null, 'Photo', false, true, true, 12),
  ('item-13', 'Aerial view', null, 'property', 'photo', '{"alt":"Placeholder: aerial view of a villa community","placeholder":"aerial"}'::jsonb, null, null, 'Photo', false, true, true, 13),
  ('item-14', 'Clinic host', null, 'ai-avatar', 'photo', '{"alt":"Placeholder: clinic AI avatar","placeholder":"avatar-clinic","bright":true}'::jsonb, null, null, 'AI avatar', false, true, true, 14),
  ('item-15', 'Coach', null, 'ai-avatar', 'photo', '{"alt":"Placeholder: coach AI avatar","placeholder":"avatar-coach","bright":true}'::jsonb, null, null, 'AI avatar', false, true, true, 15)
on conflict do nothing;

insert into public.portfolio_placements (item_id, placement, sort_order) values
  ('item-1', 'home-reels', 1),
  ('item-1', 'property-gallery-video', 1),
  ('item-1', 'work', 1),
  ('item-2', 'home-reels', 2),
  ('item-2', 'home-row-production', 2),
  ('item-2', 'production-hero', 1),
  ('item-2', 'property-gallery-video', 2),
  ('item-2', 'post-service-cards', 1),
  ('item-2', 'post-hero', 1),
  ('item-2', 'work', 2),
  ('item-3', 'home-reels', 3),
  ('item-3', 'home-row-avatars', 3),
  ('item-3', 'work', 3),
  ('item-4', 'home-reels', 4),
  ('item-4', 'production-hero', 2),
  ('item-4', 'work', 4),
  ('item-5', 'home-reels', 5),
  ('item-5', 'home-row-production', 0),
  ('item-5', 'production-hero', 0),
  ('item-5', 'property-gallery-video', 5),
  ('item-5', 'work', 5),
  ('item-6', 'home-reels', 6),
  ('item-6', 'home-row-production', 6),
  ('item-6', 'post-service-cards', 2),
  ('item-6', 'work', 6),
  ('item-7', 'property-hero', 7),
  ('item-7', 'property-gallery-photo', 0),
  ('item-7', 'work', 7),
  ('item-8', 'home-row-post', 8),
  ('item-8', 'post-service-cards', 0),
  ('item-8', 'work', 8),
  ('item-9', 'home-row-post', 9),
  ('item-9', 'property-gallery-photo', 9),
  ('item-9', 'post-hero', 0),
  ('item-9', 'work', 9),
  ('item-10', 'home-row-post', 10),
  ('item-10', 'property-gallery-photo', 10),
  ('item-10', 'work', 10),
  ('item-11', 'post-hero', 2),
  ('item-11', 'work', 11),
  ('item-12', 'property-gallery-photo', 12),
  ('item-12', 'work', 12),
  ('item-13', 'property-gallery-photo', 13),
  ('item-13', 'work', 13),
  ('item-14', 'home-row-avatars', 14),
  ('item-15', 'home-row-avatars', 15)
on conflict do nothing;

insert into public.case_studies (id, slug, client, title, hero_lines, summary, brief, what_we_did, results, quote, cover, gallery, related, category, sample, published, sort_order) values
  ('sample-brokerage-monthly', 'sample-monthly-content-for-a-brokerage', 'Dubai brokerage (sample)', 'Monthly listing content for a brokerage', array['Monthly content', 'for a brokerage.']::text[], 'Shoot days, reels and long-form walkthroughs on a monthly plan.', 'A growing brokerage needed every new listing photographed and on social media within days, without briefing a different photographer each time.', array['Set up a monthly plan of half and full shoot days across their communities.', 'Photographed each listing and cut a vertical reel and a long-form walkthrough.', 'Delivered everything to one dashboard with a monthly statement.']::text[], '[{"value":"—","label":"Listings shot per month"},{"value":"—","label":"Reels delivered"},{"value":"—","label":"Average turnaround"}]'::jsonb, null, '{"alt":"Placeholder: apartment interior from a listing shoot","placeholder":"interior"}'::jsonb, '[{"alt":"Placeholder: living room","placeholder":"interior"},{"alt":"Placeholder: kitchen","placeholder":"kitchen"},{"alt":"Placeholder: penthouse at night","placeholder":"night"}]'::jsonb, array['item-1', 'item-2', 'item-5']::text[], 'property', true, true, 1)
on conflict do nothing;

insert into public.before_after (id, tab, title, description, before, after, placeholder_before_filter, in_hero, sample, published, sort_order) values
  ('sky', 'Sky', 'Sky replacement', 'Grey or blown-out skies replaced with a natural blue sky that matches the light on the building.', '{"alt":"Villa exterior under a grey sky, before editing","placeholder":"villa-grey"}'::jsonb, '{"alt":"Same villa with a clear blue sky, after editing","placeholder":"villa"}'::jsonb, null, false, true, true, 1),
  ('twilight', 'Twilight', 'Virtual twilight', 'A daytime exterior turned into a dusk shot with warm windows and a glowing pool. The listing photo that gets the click.', '{"alt":"Villa exterior in daylight, before editing","placeholder":"villa"}'::jsonb, '{"alt":"Same villa converted to twilight, after editing","placeholder":"villa-dusk"}'::jsonb, null, false, true, true, 2),
  ('hdr', 'HDR', 'HDR blending', 'Bracketed exposures blended for bright rooms, clean window views, straight verticals and true colour.', '{"alt":"Dim living room, single exposure, before editing","placeholder":"interior"}'::jsonb, '{"alt":"Same living room after HDR blending","placeholder":"interior"}'::jsonb, 'grayscale(.55) brightness(.78) contrast(.78) saturate(.7)', true, true, true, 3)
on conflict do nothing;

insert into public.avatars (id, name, niche, poster, clip, sample, published, sort_order) values
  ('adam', 'Adam', 'Real estate · market updates', '{"alt":"Placeholder: real estate avatar","placeholder":"adam","bright":true}'::jsonb, null, true, true, 1),
  ('clinic', 'Clinic host', 'Treatments · FAQs', '{"alt":"Placeholder: clinic avatar","placeholder":"avatar-clinic","bright":true}'::jsonb, null, true, true, 2),
  ('finance', 'Finance explainer', 'Mortgages · investment', '{"alt":"Placeholder: finance avatar","placeholder":"avatar-finance"}'::jsonb, null, true, true, 3),
  ('coach', 'Coach', 'Courses · personal brand', '{"alt":"Placeholder: coach avatar","placeholder":"avatar-coach","bright":true}'::jsonb, null, true, true, 4)
on conflict do nothing;

insert into public.reviews (id, name, role, company, rating, text, source, link, placements, sample, published, sort_order) values
  ('sample-1', null, 'Leasing manager', 'Dubai brokerage', 5, 'We send the address, they handle the rest. Photos are back the next morning and the listing goes live the same day.', 'google', null, array['home']::text[], true, true, 1),
  ('sample-2', null, 'Marketing lead', 'Developer', 5, 'Twenty reels a month without us thinking about it. The content plan alone saved our marketing team hours.', 'google', null, array['home']::text[], true, true, 2),
  ('sample-3', null, 'Agent', 'Holiday homes', 5, 'Clear prices, no chasing files. Everything is in the dashboard with the invoice.', 'google', null, array['home']::text[], true, true, 3)
on conflict do nothing;

insert into public.faqs (id, page, question, answer, draft, published, sort_order) values
  ('home-1', 'home', 'Where do you work?', 'We shoot across the UAE, based in Dubai. Editing and AI avatars are fully remote, so we work with clients anywhere.', true, true, 1),
  ('home-2', 'home', 'How fast is delivery?', 'Property photos in 24 hours. Reels in 24–48 hours. Monthly packages follow an agreed content calendar.', true, true, 2),
  ('home-3', 'home', 'How does pricing work?', 'Every service page shows starting prices. The final quote is confirmed in chat or on a short call, before you pay anything.', true, true, 3),
  ('home-4', 'home', 'How do I start?', 'Send a request or WhatsApp us. We reply within 15 minutes during working hours.', true, true, 4),
  ('production-5', 'production', 'How many revisions do I get?', 'Two rounds of revisions per edit are included. Changes to the brief after shooting are quoted separately.', true, true, 5),
  ('production-6', 'production', 'What if I don''t use all my shoot days?', 'Unused shoot days can move to the next month once. We''ll remind you mid-month so nothing is wasted.', true, true, 6),
  ('production-7', 'production', 'Who owns the footage?', 'You do. Final edits and raw footage from your shoots are yours to use anywhere.', true, true, 7),
  ('production-8', 'production', 'Can I change package mid-contract?', 'Yes. Your package can grow with your listings from any month.', true, true, 8),
  ('property-shoots-9', 'property-shoots', 'How should I prepare the property?', 'Lights on, blinds open, surfaces clear, personal items away. We send a 5-point checklist when you book.', true, true, 9),
  ('property-shoots-10', 'property-shoots', 'Can I reschedule?', 'Yes, free up to 24 hours before the shoot.', true, true, 10),
  ('property-shoots-11', 'property-shoots', 'Which areas do you cover?', 'All of Dubai. Other emirates on request.', true, true, 11),
  ('property-shoots-12', 'property-shoots', 'What if the weather is bad?', 'We move exterior shots to a clear day at no cost, or replace the sky in editing.', true, true, 12),
  ('post-production-13', 'post-production', 'Can you match our current editing style?', 'Yes. Send 5–10 finished photos you like. We build a preset and a written style guide before your first batch.', true, true, 13),
  ('post-production-14', 'post-production', 'What file formats do you accept?', 'RAW brackets (CR3, NEF, ARW, DNG), JPEG, and video in any common format. Deliverables in the size and naming you need.', true, true, 14),
  ('post-production-15', 'post-production', 'How do payments work?', 'We invoice monthly after a custom quote.', true, true, 15),
  ('post-production-16', 'post-production', 'Is the free test really free?', 'Yes. After a 15-minute call we edit one listing (up to 10 photos) or one reel, free, so you can judge the quality.', true, true, 16),
  ('ai-avatars-17', 'ai-avatars', 'Will people know it''s AI?', 'Most won''t spot it. We still label AI content where platforms require it, such as Meta and TikTok, and we recommend being open about it.', true, true, 17),
  ('ai-avatars-18', 'ai-avatars', 'Who owns the avatar?', 'You do. The avatar is built for your brand and isn''t reused for anyone else.', true, true, 18),
  ('ai-avatars-19', 'ai-avatars', 'Can it speak Arabic?', 'Yes. English and Arabic are supported, and other languages on request.', true, true, 19),
  ('ai-avatars-20', 'ai-avatars', 'Can it look like me?', 'Yes, with your consent and a short photo session we can build an avatar based on you.', true, true, 20)
on conflict do nothing;

insert into public.stats (id, value, label, label_by_placement, placement_order, placements, sample, published, sort_order) values
  ('since', '2020', 'Creating content since', '{}'::jsonb, '{"post-production":4}'::jsonb, array['home', 'post-production']::text[], false, true, 1),
  ('properties', '1,000+', 'Properties shot in Dubai', '{"post-production":"Properties produced"}'::jsonb, '{"post-production":2}'::jsonb, array['home', 'post-production']::text[], false, true, 2),
  ('brands', '100+', 'Brands worked with', '{}'::jsonb, '{"post-production":3}'::jsonb, array['home', 'post-production']::text[], false, true, 3),
  ('videos', '5,000+', 'Videos edited', '{}'::jsonb, '{"post-production":1}'::jsonb, array['home', 'post-production']::text[], false, true, 4)
on conflict do nothing;

insert into public.clients (id, name, logo, published, sort_order) values
  ('xperience-realty', 'Xperience Realty', null, true, 1),
  ('k-estates', 'K Estates', null, true, 2),
  ('inhouse', 'Inhouse', null, true, 3)
on conflict do nothing;

insert into public.proof_strip_pages (page, enabled) values
  ('home', true),
  ('production', true),
  ('property-shoots', false),
  ('post-production', false),
  ('ai-avatars', false),
  ('contact', false),
  ('work', false),
  ('about', false)
on conflict do nothing;

insert into public.pricing_property (type, size_index, size_label, service, price) values
  ('apartment', 0, 'Studio', 'photo', 450),
  ('apartment', 0, 'Studio', 'short', 300),
  ('apartment', 0, 'Studio', 'lf_day', 500),
  ('apartment', 0, 'Studio', 'lf_night', 600),
  ('apartment', 0, 'Studio', 'lf_day_night', 800),
  ('apartment', 0, 'Studio', 'tour', 500),
  ('apartment', 1, '1 Bed', 'photo', 500),
  ('apartment', 1, '1 Bed', 'short', 300),
  ('apartment', 1, '1 Bed', 'lf_day', 600),
  ('apartment', 1, '1 Bed', 'lf_night', 700),
  ('apartment', 1, '1 Bed', 'lf_day_night', 950),
  ('apartment', 1, '1 Bed', 'tour', 600),
  ('apartment', 2, '2 Bed', 'photo', 550),
  ('apartment', 2, '2 Bed', 'short', 350),
  ('apartment', 2, '2 Bed', 'lf_day', 700),
  ('apartment', 2, '2 Bed', 'lf_night', 800),
  ('apartment', 2, '2 Bed', 'lf_day_night', 1100),
  ('apartment', 2, '2 Bed', 'tour', 700),
  ('apartment', 3, '3 Bed', 'photo', 650),
  ('apartment', 3, '3 Bed', 'short', 400),
  ('apartment', 3, '3 Bed', 'lf_day', 800),
  ('apartment', 3, '3 Bed', 'lf_night', 900),
  ('apartment', 3, '3 Bed', 'lf_day_night', 1200),
  ('apartment', 3, '3 Bed', 'tour', 800),
  ('apartment', 4, '4 Bed', 'photo', 750),
  ('apartment', 4, '4 Bed', 'short', 400),
  ('apartment', 4, '4 Bed', 'lf_day', 900),
  ('apartment', 4, '4 Bed', 'lf_night', 1000),
  ('apartment', 4, '4 Bed', 'lf_day_night', 1350),
  ('apartment', 4, '4 Bed', 'tour', 900),
  ('apartment', 5, '5 Bed', 'photo', 850),
  ('apartment', 5, '5 Bed', 'short', 450),
  ('apartment', 5, '5 Bed', 'lf_day', 1000),
  ('apartment', 5, '5 Bed', 'lf_night', 1200),
  ('apartment', 5, '5 Bed', 'lf_day_night', 1500),
  ('apartment', 5, '5 Bed', 'tour', 1000),
  ('villa', 0, '2 Bed', 'photo', 700),
  ('villa', 0, '2 Bed', 'short', 400),
  ('villa', 0, '2 Bed', 'lf_day', 900),
  ('villa', 0, '2 Bed', 'lf_night', 1000),
  ('villa', 0, '2 Bed', 'lf_day_night', 1250),
  ('villa', 0, '2 Bed', 'tour', 900),
  ('villa', 1, '3 Bed', 'photo', 800),
  ('villa', 1, '3 Bed', 'short', 450),
  ('villa', 1, '3 Bed', 'lf_day', 950),
  ('villa', 1, '3 Bed', 'lf_night', 1100),
  ('villa', 1, '3 Bed', 'lf_day_night', 1400),
  ('villa', 1, '3 Bed', 'tour', 950),
  ('villa', 2, '4 Bed', 'photo', 900),
  ('villa', 2, '4 Bed', 'short', 550),
  ('villa', 2, '4 Bed', 'lf_day', 1050),
  ('villa', 2, '4 Bed', 'lf_night', 1200),
  ('villa', 2, '4 Bed', 'lf_day_night', 1500),
  ('villa', 2, '4 Bed', 'tour', 1100),
  ('villa', 3, '5 Bed', 'photo', 1100),
  ('villa', 3, '5 Bed', 'short', 650),
  ('villa', 3, '5 Bed', 'lf_day', 1150),
  ('villa', 3, '5 Bed', 'lf_night', 1300),
  ('villa', 3, '5 Bed', 'lf_day_night', 1600),
  ('villa', 3, '5 Bed', 'tour', 1250),
  ('villa', 4, '6 Bed', 'photo', 1200),
  ('villa', 4, '6 Bed', 'short', 750),
  ('villa', 4, '6 Bed', 'lf_day', 1250),
  ('villa', 4, '6 Bed', 'lf_night', 1400),
  ('villa', 4, '6 Bed', 'lf_day_night', 1800),
  ('villa', 4, '6 Bed', 'tour', 1400),
  ('villa', 5, '7 Bed', 'photo', 1400),
  ('villa', 5, '7 Bed', 'short', 800),
  ('villa', 5, '7 Bed', 'lf_day', 1350),
  ('villa', 5, '7 Bed', 'lf_night', 1600),
  ('villa', 5, '7 Bed', 'lf_day_night', 2000),
  ('villa', 5, '7 Bed', 'tour', 1500)
on conflict do nothing;

insert into public.pricing_commercial_tiers (tier_index, label, description, popular, photo, short, long, tour, photos, reel, walkthrough, tour_hotspots) values
  (0, 'Basic', 'Small spaces', false, 450, 300, null, null, 'Up to 15', '30–45 s', null, null),
  (1, 'Essential', 'Most offices', true, 550, 350, 600, 600, 'Up to 20', '45–60 s', '3–5 min', '8–10 hotspots'),
  (2, 'Premium', 'Large commercial spaces', false, 700, 450, 800, 800, 'Up to 30', '60–75 s', '5–10 min', 'Up to 15 hotspots'),
  (3, 'Executive', 'HQ / warehouses', false, 850, 500, 1000, 1000, 'Up to 40', '60–90 s', '8–15 min', 'Up to 20 hotspots')
on conflict do nothing;

insert into public.pricing_twilight (grp, qty, price) values
  ('standard', 5, 120),
  ('standard', 10, 220),
  ('standard', 20, 400),
  ('villa', 5, 150),
  ('villa', 10, 275),
  ('villa', 20, 500)
on conflict do nothing;

insert into public.pricing_other (key, value) values
  ('property_meta', '{"currency":"AED","apartment":{"label":"Apartment","defaultSize":1},"villa":{"label":"Villa / townhouse","defaultSize":0},"commercial":{"label":"Commercial","defaultTier":1},"delivery":{"photo":"24h","short":"24–48h","long":"24–48h","tour":"48–72h"}}'::jsonb),
  ('production', '{"fromMonthly":4000,"chips":["Shoot days","Edited reels","Long-form video","Photography","360 tours"]}'::jsonb),
  ('post_production', '{"currency":"USD","rates":[{"key":"photo","name":"Photo edits","amount":0.8,"unit":"HDR photo","bullets":["Bracket blending and window pulls","Sky replacement and declutter","Twilight on request"]},{"key":"short","name":"Short-form","amount":50,"unit":"reel","bullets":["Reels up to 60 seconds","Music, captions and branding","Formatted for every platform"]},{"key":"long","name":"Long-form","amount":150,"unit":"video","bullets":["YouTube videos up to 10 minutes","B-roll, graphics and titles","Thumbnail on request"]}],"note":"Rates in USD. Your final quote depends on volume, style and turnaround, and we can quote in your currency on the call."}'::jsonb),
  ('ai_avatars', '{"launchLine":"Launch pricing · set on your demo call","extraAvatarNote":"Each extra avatar is added with its own setup fee.","tiers":[{"name":"Avatar setup","cadence":"One-off","bullets":["Custom face and look","Voice selection","3 test videos","Yours to keep"]},{"name":"Videos","cadence":"Monthly","bullets":["Everything in setup","Monthly video bundle","Captions and branding","You send scripts or topics"]},{"name":"Videos + strategy","cadence":"Monthly","bullets":["Everything in Videos","Content strategy","We write every script","Monthly performance review"]}]}'::jsonb)
on conflict do nothing;

insert into public.site_settings (key, value) values
  ('site', '{"company":"Milkywayy LLC","licence":"Sharjah Media City","addressLine":"Dubai, UAE","whatsapp":{"number":"971507263306","display":"+971 50 726 3306"},"email":"hello@milkywayy.com","instagram":{"handle":"@milkywayy_com","url":"https://www.instagram.com/milkywayy_com"},"linkedin":{"handle":"milkywayy-com","url":"https://www.linkedin.com/company/milkywayy-com"},"googleRating":{"value":5,"count":null},"founder":{"name":"Akash Praseed","role":"Founder, Milkywayy","quote":"After years of creating content, we know where production slows down: the follow-ups, the revisions, the back-and-forth. So we''re building systems that take them out. You book, we shoot, you download.","photo":{"src":"/founder.webp","alt":"Akash Praseed, founder of Milkywayy","focus":"55% 15%"}},"showreel":{"alt":"Showreel placeholder: Dubai skyline at dusk","placeholder":"dusk","duration":"0:45"},"booking":{"slots":["Morning","Afternoon","Evening"],"closedWeekdays":[0],"windowDays":60,"multiPropertyNote":"Shooting more than one property on the same day or in the same area? We''ll send you a better price for the whole booking in the same chat."},"proofStripPages":["home","production"],"footerLine":"A Dubai content studio. Production in the UAE, editing and AI presenters worldwide."}'::jsonb),
  ('avatar_hero', '{"name":"Adam","poster":{"alt":"Placeholder: Adam, AI presenter, in a bright loft","placeholder":"adam","bright":true},"timecode":"REC 00:00:07:12","captionLead":"Dubai rents are up again this quarter. Here''s what that means","captionHighlight":"for buyers.","revealTitle":"100% AI","revealText":"Face, voice and gestures generated · edited by Milkywayy","proofLead":"Clients shown Adam","proofHighlight":"didn''t spot he was AI","sample":true}'::jsonb)
on conflict do nothing;

commit;
