import type { PortfolioItem } from "./types";

// TODO(owner): real portfolio media (reels, photos, long-form). Placeholders until supplied.
let n = 0;
const item = (p: Omit<PortfolioItem, "id" | "published" | "sortOrder">): PortfolioItem => ({
  ...p,
  id: `item-${++n}`,
  published: true,
  sortOrder: n,
  sample: true,
});

export const portfolio: PortfolioItem[] = [
  item({
    title: "Palm Jumeirah villa",
    category: "property",
    format: "reel",
    duration: "0:30",
    meta: "Property",
    media: { alt: "Placeholder reel: villa with pool", placeholder: "villa" },
    placements: ["home-reels", "property-gallery-video", "work"],
  }),
  item({
    title: "Downtown penthouse",
    category: "property",
    format: "reel",
    duration: "0:24",
    meta: "Night",
    media: { alt: "Placeholder reel: penthouse at night", placeholder: "night" },
    placements: [
      "home-reels",
      "home-row-production",
      "production-hero",
      "property-gallery-video",
      "post-service-cards",
      "work",
    ],
    placementOrder: { "production-hero": 1, "post-service-cards": 1 },
  }),
  item({
    title: "Adam, market update",
    category: "ai-avatar",
    format: "reel",
    meta: "AI avatar",
    tag: "Adam · AI",
    media: { alt: "Placeholder: AI presenter Adam", placeholder: "adam", bright: true },
    placements: ["home-reels", "home-row-avatars", "work"],
  }),
  item({
    title: "Aesthetic clinic",
    category: "brand",
    format: "reel",
    duration: "0:40",
    meta: "Brand",
    media: { alt: "Placeholder reel: clinic interior", placeholder: "clinic" },
    placements: ["home-reels", "production-hero", "work"],
    placementOrder: { "production-hero": 2 },
  }),
  item({
    title: "Marina 2BR walkthrough",
    category: "property",
    format: "reel",
    duration: "0:28",
    meta: "Property",
    tag: "Marina 2BR",
    media: { alt: "Placeholder: apartment interior", placeholder: "interior" },
    placements: [
      "home-reels",
      "home-row-production",
      "production-hero",
      "property-gallery-video",
      "work",
    ],
    placementOrder: { "home-row-production": 0, "production-hero": 0 },
  }),
  item({
    title: "Barber studio",
    category: "brand",
    format: "reel",
    duration: "0:35",
    meta: "Brand",
    media: { alt: "Placeholder: salon brand reel", placeholder: "salon" },
    placements: ["home-reels", "home-row-production", "post-service-cards", "work"],
    placementOrder: { "post-service-cards": 2 },
  }),
  item({
    title: "Living room, Dubai Marina 2BR",
    category: "property",
    format: "photo",
    tag: "Dubai Marina · 2BR",
    meta: "Photo",
    media: { alt: "Placeholder: living room of a 2-bedroom apartment", placeholder: "interior" },
    placements: ["property-hero", "property-gallery-photo", "work"],
    placementOrder: { "property-gallery-photo": 0 },
  }),
  item({
    title: "Villa twilight",
    category: "editing",
    format: "photo",
    tag: "Twilight",
    meta: "Editing",
    media: { alt: "Placeholder: twilight conversion of a villa", placeholder: "villa-dusk" },
    placements: ["home-row-post", "post-service-cards", "work"],
    placementOrder: { "post-service-cards": 0 },
  }),
  item({
    title: "HDR kitchen",
    category: "editing",
    format: "photo",
    meta: "Editing",
    media: { alt: "Placeholder: HDR kitchen", placeholder: "kitchen" },
    placements: ["home-row-post", "property-gallery-photo", "work"],
  }),
  item({
    title: "HDR bathroom",
    category: "editing",
    format: "photo",
    meta: "Editing",
    media: { alt: "Placeholder: HDR bathroom", placeholder: "bath" },
    placements: ["home-row-post", "property-gallery-photo", "work"],
  }),
  item({
    title: "Villa pool",
    category: "property",
    format: "photo",
    meta: "Photo",
    media: { alt: "Placeholder: villa pool", placeholder: "villa" },
    placements: ["property-gallery-photo", "work"],
  }),
  item({
    title: "Aerial view",
    category: "property",
    format: "photo",
    meta: "Photo",
    media: { alt: "Placeholder: aerial view of a villa community", placeholder: "aerial" },
    placements: ["property-gallery-photo", "work"],
  }),
  item({
    title: "Clinic host",
    category: "ai-avatar",
    format: "photo",
    meta: "AI avatar",
    media: { alt: "Placeholder: clinic AI avatar", placeholder: "avatar-clinic", bright: true },
    placements: ["home-row-avatars"],
  }),
  item({
    title: "Coach",
    category: "ai-avatar",
    format: "photo",
    meta: "AI avatar",
    media: { alt: "Placeholder: coach AI avatar", placeholder: "avatar-coach", bright: true },
    placements: ["home-row-avatars"],
  }),
];
