/**
 * Builds supabase/seed.sql from the typed seed data in content/ (guide §0: content/ fills the
 * database on first run). Every insert is `on conflict do nothing`, so re-running never overwrites
 * what the owner has edited in the admin.
 *
 *   npm run db:seed:sql      → writes supabase/seed.sql (then apply it to the project)
 *
 * Runs on Node 24's built-in TypeScript support; content files only use `import type`.
 */
import { writeFileSync } from "node:fs";
import { avatarHero, avatars } from "../content/avatars.ts";
import { beforeAfter } from "../content/beforeAfter.ts";
import { caseStudies } from "../content/caseStudies.ts";
import { clients } from "../content/clients.ts";
import { faqs } from "../content/faqs.ts";
import { portfolio } from "../content/portfolio.ts";
import { otherPricing, propertyPricing } from "../content/pricing.ts";
import { reviews } from "../content/reviews.ts";
import { siteSettings } from "../content/site.ts";
import { stats } from "../content/stats.ts";

type Val = string | number | boolean | null | undefined | object | string[];

const q = (v: Val): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "string") return `'${v.replace(/'/g, "''")}'`;
  return `${q(JSON.stringify(v))}::jsonb`;
};
const arr = (v: string[] | undefined): string =>
  v && v.length ? `array[${v.map((x) => q(x)).join(", ")}]::text[]` : "'{}'::text[]";

const out: string[] = [
  "-- Generated by scripts/seed.mts from content/. Do not edit by hand; re-run the script.",
  "begin;",
];
const insert = (table: string, rows: Record<string, string>[], conflict = "do nothing") => {
  if (!rows.length) return;
  const cols = Object.keys(rows[0]);
  out.push(
    `insert into public.${table} (${cols.join(", ")}) values\n` +
      rows.map((r) => `  (${cols.map((c) => r[c]).join(", ")})`).join(",\n") +
      `\non conflict ${conflict};`,
  );
};

insert(
  "portfolio_items",
  portfolio.map((p) => ({
    id: q(p.id),
    title: q(p.title),
    client: q(p.client),
    category: q(p.category),
    format: q(p.format),
    media: q(p.media),
    duration: q(p.duration),
    tag: q(p.tag),
    meta: q(p.meta),
    featured: q(!!p.featured),
    sample: q(!!p.sample),
    published: q(p.published),
    sort_order: q(p.sortOrder),
  })),
);
insert(
  "portfolio_placements",
  portfolio.flatMap((p) =>
    p.placements.map((pl) => ({
      item_id: q(p.id),
      placement: q(pl),
      sort_order: q(p.placementOrder?.[pl] ?? p.sortOrder),
    })),
  ),
);
insert(
  "case_studies",
  caseStudies.map((c) => ({
    id: q(c.id),
    slug: q(c.slug),
    client: q(c.client),
    title: q(c.title),
    hero_lines: c.heroLines ? arr(c.heroLines) : "null",
    summary: q(c.summary),
    brief: q(c.brief),
    what_we_did: arr(c.whatWeDid),
    results: q(c.results),
    quote: c.quote ? q(c.quote) : "null",
    cover: q(c.cover),
    gallery: q(c.gallery),
    related: arr(c.related),
    category: q(c.category),
    sample: q(!!c.sample),
    published: q(c.published),
    sort_order: q(c.sortOrder),
  })),
);
insert(
  "before_after",
  beforeAfter.map((b) => ({
    id: q(b.id),
    tab: q(b.tab),
    title: q(b.title),
    description: q(b.description),
    before: q(b.before),
    after: q(b.after),
    placeholder_before_filter: q(b.placeholderBeforeFilter),
    in_hero: q(!!b.inHero),
    sample: q(!!b.sample),
    published: q(b.published),
    sort_order: q(b.sortOrder),
  })),
);
insert(
  "avatars",
  avatars.map((a) => ({
    id: q(a.id),
    name: q(a.name),
    niche: q(a.niche),
    poster: q(a.poster),
    clip: q(a.clip),
    sample: q(!!a.sample),
    published: q(a.published),
    sort_order: q(a.sortOrder),
  })),
);
insert(
  "reviews",
  reviews.map((r) => ({
    id: q(r.id),
    name: q(r.name),
    role: q(r.role),
    company: q(r.company),
    rating: q(r.rating),
    text: q(r.text),
    source: q(r.source),
    link: q(r.link),
    placements: arr(r.placements),
    sample: q(!!r.sample),
    published: q(r.published),
    sort_order: q(r.sortOrder),
  })),
);
insert(
  "faqs",
  faqs.map((f) => ({
    id: q(f.id),
    page: q(f.page),
    question: q(f.question),
    answer: q(f.answer),
    draft: q(f.draft),
    published: q(f.published),
    sort_order: q(f.sortOrder),
  })),
);
insert(
  "stats",
  stats.map((s) => ({
    id: q(s.id),
    value: q(s.value),
    label: q(s.label),
    label_by_placement: q(s.labelByPlacement ?? {}),
    placement_order: q(s.placementOrder ?? {}),
    placements: arr(s.placements),
    sample: q(!!s.sample),
    published: q(s.published),
    sort_order: q(s.sortOrder),
  })),
);
insert(
  "clients",
  clients.map((c) => ({
    id: q(c.id),
    name: q(c.name),
    logo: q(c.logo),
    published: q(c.published),
    sort_order: q(c.sortOrder),
  })),
);
const PAGES = [
  "home",
  "production",
  "property-shoots",
  "post-production",
  "ai-avatars",
  "contact",
  "work",
  "about",
];
insert(
  "proof_strip_pages",
  PAGES.map((p) => ({ page: q(p), enabled: q(siteSettings.proofStripPages.includes(p as never)) })),
);

// Pricing
const SERVICE_KEYS = [
  ["photo", (s: (typeof propertyPricing.apartment.sizes)[number]) => s.photo],
  ["short", (s: (typeof propertyPricing.apartment.sizes)[number]) => s.short],
  ["lf_day", (s: (typeof propertyPricing.apartment.sizes)[number]) => s.long.day],
  ["lf_night", (s: (typeof propertyPricing.apartment.sizes)[number]) => s.long.night],
  ["lf_day_night", (s: (typeof propertyPricing.apartment.sizes)[number]) => s.long.dayNight],
  ["tour", (s: (typeof propertyPricing.apartment.sizes)[number]) => s.tour],
] as const;
insert(
  "pricing_property",
  (["apartment", "villa"] as const).flatMap((type) =>
    propertyPricing[type].sizes.flatMap((size, i) =>
      SERVICE_KEYS.map(([service, get]) => ({
        type: q(type),
        size_index: q(i),
        size_label: q(size.label),
        service: q(service),
        price: q(get(size)),
      })),
    ),
  ),
);
insert(
  "pricing_commercial_tiers",
  propertyPricing.commercial.tiers.map((t, i) => ({
    tier_index: q(i),
    label: q(t.label),
    description: q(t.description),
    popular: q(!!t.popular),
    photo: q(t.photo),
    short: q(t.short),
    long: q(t.long),
    tour: q(t.tour),
    photos: q(t.includes.photos),
    reel: q(t.includes.reel),
    walkthrough: q(t.includes.walkthrough),
    tour_hotspots: q(t.includes.tourHotspots),
  })),
);
insert(
  "pricing_twilight",
  (["standard", "villa"] as const).flatMap((grp) =>
    ([5, 10, 20] as const).map((qty) => ({
      grp: q(grp),
      qty: q(qty),
      price: q(propertyPricing.twilight[grp][qty]),
    })),
  ),
);
insert("pricing_other", [
  {
    key: q("property_meta"),
    value: q({
      currency: propertyPricing.currency,
      apartment: {
        label: propertyPricing.apartment.label,
        defaultSize: propertyPricing.apartment.defaultSize,
      },
      villa: { label: propertyPricing.villa.label, defaultSize: propertyPricing.villa.defaultSize },
      commercial: {
        label: propertyPricing.commercial.label,
        defaultTier: propertyPricing.commercial.defaultTier,
      },
      delivery: propertyPricing.delivery,
    }),
  },
  { key: q("production"), value: q(otherPricing.production) },
  { key: q("post_production"), value: q(otherPricing.postProduction) },
  { key: q("ai_avatars"), value: q(otherPricing.aiAvatars) },
]);

// Settings
insert("site_settings", [
  { key: q("site"), value: q(siteSettings) },
  { key: q("avatar_hero"), value: q(avatarHero) },
]);

out.push("commit;");
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out.join("\n\n") + "\n");
console.log(`Wrote supabase/seed.sql (${out.length - 2} statements)`);
